### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by iSongWorld** [Zewo/File#1]
There were an error occurred when I compiling on Ubuntu 14.04, seems something libs didn't installed.

/root/swift/Server/Packages/File-0.2.5/Source/File.swift:59:23: error: use of undeclared type 'mfile'
    private var file: mfile
                      ^~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:64:28: error: use of unresolved identifier 'filetell'
        let position = Int(filetell(file))
                           ^~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:70:28: error: use of unresolved identifier 'fileseek'
        let position = Int(fileseek(file, off_t(position)))
                           ^~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:76:16: error: use of unresolved identifier 'fileeof'
        return fileeof(file) != 0
               ^~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:101:29: error: use of unresolved identifier 'fileopen'
        try self.init(file: fileopen(path, mode.value, S_IRUSR | S_IWUSR | S_IRGRP | S_IROTH))
                            ^~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:106:29: error: use of unresolved identifier 'fileattach'
        try self.init(file: fileattach(fileDescriptor))
                            ^~~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:111:13: error: use of unresolved identifier 'fileclose'
            fileclose(file)
            ^~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:119:13: error: use of unresolved identifier 'filewrite'
            filewrite(file, $0.baseAddress, $0.count, deadline)
            ^~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:134:13: error: use of unresolved identifier 'fileread'
            fileread(file, $0.baseAddress, $0.count, deadline)
            ^~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:146:13: error: use of unresolved identifier 'filereadlh'
            filereadlh(file, $0.baseAddress, lowWaterMark, highWaterMark, deadline)
            ^~~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:169:9: error: use of unresolved identifier 'fileflush'
        fileflush(file, deadline)
        ^~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:178:16: error: use of unresolved identifier 'fileattach'
        file = fileattach(fileDescriptor)
               ^~~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:186:16: error: use of unresolved identifier 'filedetach'
        return filedetach(file)
               ^~~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:195:9: error: use of unresolved identifier 'fileclose'
        fileclose(file)
        ^~~~~~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:59:23: error: use of undeclared type 'mfile'
    private var file: mfile
                      ^~~~~
/root/swift/Server/Packages/File-0.2.5/Source/File.swift:95:16: error: use of undeclared type 'mfile'
    init(file: mfile) throws {
               ^~~~~

**Comment by Danappelxx** [comment]
Hi. You need to install the C dependencies that Zewo has before you can use some of the libraries. File requires `libvenice` (a fork of libmill). You can install it like so:

```shell
echo "deb [trusted=yes] http://apt.zewo.io/deb ./" | sudo tee --append /etc/apt/sources.list
sudo apt-get update
sudo apt-get install libvenice
```

**Comment by iSongWorld** [comment]
Thank you for answering. After installing the libvenice everything works fine yet. Really appreciate it.

**Comment by Danappelxx** [comment]
No problem! :smiley:
